package com.survey.copy;

import java.util.Arrays;
import java.util.List;

import com.fasterxml.jackson.databind.ObjectMapper;

public class TestSurveyQestionAnswerOptionsCombo {

	public static void main(String[] args) {
		List formSurveyList = queryGetResultList();
		FormSurveyDto formSurveyDto = CopyToFormSurveyEntityUtil.populateFormSurveyDetails(formSurveyList);// PASCP//PriorAuthSosClinicalPolicy
		System.out.println(formSurveyDto);

		try {

			ObjectMapper objectMapper = new ObjectMapper();
			String jsonString = objectMapper.writeValueAsString(formSurveyDto);

			System.out.println(jsonString);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private static List<Object[]> queryGetResultList() {

		List<Object[]> surveyDataList = Arrays.asList(new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP",
				"2024-07-10 00:00:00.000", "SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null,
				"color-10", "secondary_2", null, 303, "C0001_3",
				"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
				null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
				"Multi Selection with Input Option and all the options displayed Vertically", null,
				"Multiple Option can be selected including input text field", 1,
				"Have a systemic cancer and on active treatment and are re-staging", "1", "font-icon-sun-solid",
				"sun: solid", null, null, null, null, 735, null, 33, "735, 736", "MET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 2,
						"Have a known chronic disease undergoing active treatment", "2", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 736, null, 33, "735, 736", "MET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 3,
						"Performing the procedure in office or freestanding facility will delay care or adversely impact health outcomes",
						"3", "font-icon-sun-solid", "sun: solid", null, null, null, null, 737, null, 33, "735, 736",
						"MET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 4,
						"Patient does not meet above critera or unknown", "PTNOTMETCRITERIA", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 738, null, 33, "735, 736", "MET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 1,
						"Have a systemic cancer and on active treatment and are re-staging", "1", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 735, null, 34, "735, 737", "MET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 2,
						"Have a known chronic disease undergoing active treatment", "2", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 736, null, 34, "735, 737", "MET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 3,
						"Performing the procedure in office or freestanding facility will delay care or adversely impact health outcomes",
						"3", "font-icon-sun-solid", "sun: solid", null, null, null, null, 737, null, 34, "735, 737",
						"MET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 4,
						"Patient does not meet above critera or unknown", "PTNOTMETCRITERIA", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 738, null, 34, "735, 737", "MET", "STOP", null, null },

				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 1,
						"Have a systemic cancer and on active treatment and are re-staging", "1", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 735, null, 35, "736, 737", "MET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 2,
						"Have a known chronic disease undergoing active treatment", "2", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 736, null, 35, "736, 737", "MET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 3,
						"Performing the procedure in office or freestanding facility will delay care or adversely impact health outcomes",
						"3", "font-icon-sun-solid", "sun: solid", null, null, null, null, 737, null, 35, "736, 737",
						"MET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 4,
						"Patient does not meet above critera or unknown", "PTNOTMETCRITERIA", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 738, null, 35, "736, 737", "MET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 1,
						"Have a systemic cancer and on active treatment and are re-staging", "1", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 735, null, 36, "735, 736, 737", "MET", "STOP", null,
						null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 2,
						"Have a known chronic disease undergoing active treatment", "2", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 736, null, 36, "735, 736, 737", "MET", "STOP", null,
						null },

				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 3,
						"Performing the procedure in office or freestanding facility will delay care or adversely impact health outcomes",
						"3", "font-icon-sun-solid", "sun: solid", null, null, null, null, 737, null, 36, "735, 736, 737",
						"MET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 4,
						"Patient does not meet above critera or unknown", "PTNOTMETCRITERIA", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 738, null, 36, "735, 736, 737", "MET", "STOP", null,
						null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 1,
						"Have a systemic cancer and on active treatment and are re-staging", "1", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 735, null, 37, "DEFAULT", "NOTMET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 2,
						"Have a known chronic disease undergoing active treatment", "2", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 736, null, 37, "DEFAULT", "NOTMET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 3,
						"Performing the procedure in office or freestanding facility will delay care or adversely impact health outcomes",
						"3", "font-icon-sun-solid", "sun: solid", null, null, null, null, 737, null, 37, "DEFAULT",
						"NOTMET", "STOP", null, null },
				new Object[] { "PriorAuthClinicalPolicy", "1", null, "PACP", "2024-07-10 00:00:00.000",
						"SAFL:N:Save and finish later", "C0001_Test", null, 1, null, null, "color-10", "secondary_2",
						null, 303, "C0001_3",
						"Does the patient have the following medical needs, conditions, or situations which require the same equipment and/or imaging protocols to replicate past imaging:",
						null, 3, "C0001_3", null, null, "N", null, null, null, "MSIOV",
						"Multi Selection with Input Option and all the options displayed Vertically", null,
						"Multiple Option can be selected including input text field", 4,
						"Patient does not meet above critera or unknown", "PTNOTMETCRITERIA", "font-icon-sun-solid",
						"sun: solid", null, null, null, null, 738, null, 37, "DEFAULT", "NOTMET", "STOP", null, null });

		return surveyDataList;
	}

}
